#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroid.Resource", IsApplication=true)]

namespace XamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int accentColor = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int darkColor = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int lightColor = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int primaryColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryColorAlt = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int secondaryColor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int secondaryColorAlt = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int computer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logotype_grey = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logotype_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int welcome = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070012
			public const int btnLoginForgotPassword = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int btnLoginUser = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int edittextLoginName = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int edittextLoginPassword = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int linearlayoutCustomRow = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int lsCatalogCustom = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int txtCampaigSubscribersTitle = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int txtCampaignCategory = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int txtCampaignDateDay = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int txtCampaignDateMonth = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int txtCampaignDescription = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int txtCampaignName = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int txtCampaignSubscribers = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int txtItemSubtitle = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int txtItemTitle = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int txtLoginName = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int txtLoginPassword = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int txtLoginSlogan = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int viewSolid = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Campaign = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Catalog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomListRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int applicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int btnLoginForgotPassword = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnLoginUser = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int dlgForgotContent = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int dlgForgotTitle = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int dlgNegativeButton = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int dlgOutgoingLink = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int dlgPositiveButton = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int isActiveFalse = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int isActiveTrue = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int txtCampaigSubscribersTitle = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int txtCampaignClicksTitle = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int txtCampaignDateTitle = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int txtCampaignIsActiveTitle = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int txtItemSubtitle = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int txtItemTitle = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int txtLoginName = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int txtLoginPassword = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int txtLoginSlogan = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Marvelous = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int campaignActivity = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int customListRow = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int layoutDate = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int layoutSubscribers = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int loginActivity = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int loginButton = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int loginForgot = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int loginInput = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int loginLabel = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int loginSlogan = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int txtCampaignCategory = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int txtCampaignContent = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int txtCampaignDescription = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int txtCampaignName = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int txtCampaignSubtitle = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int txtItemSubtitle = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int txtItemTitle = 2131099656;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
